title: Mohammed Shuaib Ur Rehman # your name (or website title) here
logo: "/Rehman.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Frontend Engineer
  <br><br>
  <a href="mailto:shuaibindia007@gmail.com">shuaibindia007@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/shuaibindia/">LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/shuaibindia007/">Github</a> 
theme: jekyll-theme-time-machine
